### ISSUE TITLE
new action type state_timeout is not declared in the specs 

### ISSUE THREAD

**Issue by flaviogrossi** [ericentin/gen_state_machine#10]
newest otp has a [new action type](https://github.com/erlang/otp/blob/0b1fe37dbcfaad9b28ef529aa4f7b4be60ec5da8/lib/stdlib/src/gen_statem.erl#L157) `state_timeout` which is not declared in [GenStateMachine](https://github.com/antipax/gen_state_machine/blob/34b0421b88d43fdbcff47ebd901efba58b487fc7/lib/gen_state_machine.ex#L342) and this makes dialyzer emit a warning (even though everything works).

**Comment by ericentin** [comment]
@flaviogrossi thanks for the report! Would you like to do the PR as well?

**Comment by flaviogrossi** [comment]
yeah, i can try that.
I see many gen_statem types are exported now, so i think it may be good to use that instead of redeclaring them to avoid having this problem again in the future. My only doubt is: what happens to the typedocs in this case?

For example, if i use `:gen_statem.action` instead of redeclaring it should i just delete the corresponding `@typedoc`?

**Comment by ericentin** [comment]
If that still links to the appropriate typedoc somehow, then yes, otherwise, let's declare our own type aliases, and document those with a link to the appropriate documentation.

**Comment by flaviogrossi** [comment]
i opened a pr which uses remote types from gen_statem when possible.
Let me know if you find any issues with it.
Thanks
