### ISSUE TITLE
:state_enter events not supported

### ISSUE THREAD

**Issue by jvantuyl** [ericentin/gen_state_machine#22]
Title says it all.  Right now, I'm simulating `:state_enter` by stuffing an event in every time I change states.  This is error prone.  Seems to be a pretty simple fix and there's a branch out at  jakeprem/gen_state_machine@b50ed7b07761303f61d4cceaa3562b4dc11c9141.

**Comment by ericentin** [comment]
Just published v2.1.0 that contains these changes. Thanks for the feedback!
