### ISSUE TITLE
Valid actions that a state enter func can return?

### ISSUE THREAD

**Issue by acco** [ericentin/gen_state_machine#27]
Hey there! Thanks for your work here, really enjoying.

I'm having issues with allowed actions returned by enter handlers. I've stared long and hard at the Erlang docs and just can't reason my way around this one.

I'm using state enter actions:

```elixir
use GenStateMachine, callback_mode: [:handle_event_function, :state_enter]
```

This state machine is mostly _internally driven_. So as I transition between states, I want to fire off internal actions that drive the state machine forward.

If I use the `state_timeout` action from inside of an `:enter`, works just fine:

```elixir
  def handle_event(:enter, _event, :await_token, _data) do
    actions = [{:state_timeout, 0, :consume_token}]
    {:keep_state_and_data, actions}
  end
```

But it seems very picky about event types returned by enter handlers. When I try this:

```elixir
  def handle_event(:enter, _event, :await_token, _data) do
    actions = [{:next_event, :internal, :consume_token}]
    {:keep_state_and_data, actions}
  end
```

I get this:

```elixir
 Erlang error: {:bad_state_enter_action_from_state_function, {:next_event, :internal, :consume_token}}
```

I'm seeing conflicting information regarding what kinds of actions are allowed here?

Any pointers appreciated, thanks!

A

**Comment by ericentin** [comment]
Hi, since this is not an issue with this project (an Elixir wrapper for Erlang's `gen_statem`), I will have to close this issue. I would suggest the erlang questions mailing list or another forum of the sort for general Erlang questions.
