### ISSUE TITLE
Test errors for Erlang OTP 19.1 and above 

### ISSUE THREAD

**Issue by weixiyen** [ericentin/gen_state_machine#7]
Using Erlang 19.1-3 Mac OSX 64-bit from 
https://www.erlang-solutions.com/resources/download.html

```
15:04:04.796 [error] GenStateMachine #PID<0.237.0> terminating
** (ErlangError) erlang error: {:bad_return_from_init, {:handle_event_function, nil, nil}}
    (stdlib) gen_statem.erl:596: :gen_statem.init_result/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
State: :undefined
Callback mode: :undefined

15:04:04.796 [error] GenStateMachine #PID<0.238.0> terminating
** (ErlangError) erlang error: {:bad_return_from_init, {:state_functions, nil, nil}}
    (stdlib) gen_statem.erl:596: :gen_statem.init_result/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
State: :undefined
Callback mode: :undefined
```

Tests pass but that error is thrown

**Comment by bitwalker** [comment]
Looks to me like when `callback_mode` is `:state_functions`, it shouldn't be returning nil for the initial state, as it's expected to be an atom representing the initial state function to call - but that doesn't explain the failure when `callback_mode` is `handle_event_function`, where both `state` and `data` can be any term.

**Comment by ericentin** [comment]
I'm pretty sure that error is expected, the test tests other things. As long as all the tests are succeeding and the assertions are good, I'm not too concerned. If anyone wants to refactor the tests so they don't print anything, I would be more than happy to accept a PR. Let me know if I'm missing anything...

**Comment by bitwalker** [comment]
@antipax Apparently this is happening in Swarm, as described [here](https://github.com/bitwalker/swarm/issues/29). I haven't seen it myself, any ideas?

**Comment by ericentin** [comment]
I haven't seen it either in heavy use in production...

**Comment by InoMurko** [comment]
This was happening to us also - directly after Erlang upgrade.
http://erlang.org/download/otp_src_19.1.readme

OTP-13752    Application(s): stdlib

               *** POTENTIAL INCOMPATIBILITY ***

               gen_statem has been changed to set the callback mode
               for a server to what Module:callback_mode/0 returns.
               This facilitates e.g code downgrade since the callback
               mode now becomes a property of the currently active
               code, not of the server process.

               Exception handling from Module:init/1 has also been
               improved.

**Comment by ericentin** [comment]
@InoMurko Are you sure you're using the latest version of gen_state_machine? I already addressed that change some time ago.

**Comment by InoMurko** [comment]
2.0
